# Generated by Django 2.2.3 on 2019-09-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notice',
            table='notification_notice',
        ),
        migrations.AlterModelTable(
            name='noticelastseen',
            table='notification_noticelastseen',
        ),
        migrations.AlterModelTable(
            name='noticequeuebatch',
            table='notification_noticequeuebatch',
        ),
        migrations.AlterModelTable(
            name='noticesetting',
            table='notification_noticesetting',
        ),
        migrations.AlterModelTable(
            name='noticetype',
            table='notification_noticetype',
        ),
    ]
