# Generated by Django 2.2.3 on 2019-10-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_notifications', '0002_auto_20190922_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticesetting',
            name='medium',
            field=models.CharField(choices=[(0, 'email'), (1, 'onsite')], max_length=1, verbose_name='medium'),
        ),
    ]
