# Generated by Django 2.2.6 on 2019-10-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_notifications', '0003_auto_20191003_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticetype',
            name='description',
            field=models.CharField(max_length=250, verbose_name='description'),
        ),
    ]
